// 连接mysql参数
const MYSQL_CONNECT_HOST = "localhost";
const MYSQL_CONNECT_PORT = "3306";
const MYSQL_CONNECT_USER = "root";
const MYSQL_CONNECT_PASSWORD = "123456";
const MYSQL_CONNECT_DATABASE = "wxvote";

module.exports = {
  MYSQL_CONNECT_HOST,
  MYSQL_CONNECT_PORT,
  MYSQL_CONNECT_USER,
  MYSQL_CONNECT_PASSWORD,
  MYSQL_CONNECT_DATABASE,
};
